### PR TITLE
Feature/id mocking for test classes

### PR DESCRIPTION
**Pull request by KhinHou**
- adding the ability to mock Ids for test records if records don't need to be inserted into the database
- improving test coverage for AbstractSObjectTestFactory

@gavinhughpalmer Not sure how to write test classes for the two Inserter classes that extend Insertable, any pointers?

### CODE REVIEW

**Comment by gavinhughpalmer** [comment]
@KhinHou I think you could test by checking the limits around them, ie the DML statement should decrease. And in the mock version this should not change at all

**Comment by gavinhughpalmer** [comment]
@KhinHou I have made some updates to the package, where now the documentation will be generated by an automated process (based of class headers), so I have retrospectively gone through the classes and moved them into a standardised format (ie following the apex docs standard) which is slightly different to how they are being used now. Can you look to align the headers you have? This mainly includes, adding an @date in the header, removing the change log in the header (this should be handled by git if anyone needs to see this) and where appropriate adding an @group tag (I have mainly followed the folders these are in for now)

**Comment by KhinHou** [comment]
> @KhinHou I have made some updates to the package, where now the documentation will be generated by an automated process (based of class headers), so I have retrospectively gone through the classes and moved them into a standardised format (ie following the apex docs standard) which is slightly different to how they are being used now. Can you look to align the headers you have? This mainly includes, adding an @Date in the header, removing the change log in the header (this should be handled by git if anyone needs to see this) and where appropriate adding an @group tag (I have mainly followed the folders these are in for now)



> @KhinHou I have made some updates to the package, where now the documentation will be generated by an automated process (based of class headers), so I have retrospectively gone through the classes and moved them into a standardised format (ie following the apex docs standard) which is slightly different to how they are being used now. Can you look to align the headers you have? This mainly includes, adding an @Date in the header, removing the change log in the header (this should be handled by git if anyone needs to see this) and where appropriate adding an @group tag (I have mainly followed the folders these are

**Comment by KhinHou** [comment]
> @KhinHou I have made some updates to the package, where now the documentation will be generated by an automated process (based of class headers), so I have retrospectively gone through the classes and moved them into a standardised format (ie following the apex docs standard) which is slightly different to how they are being used now. Can you look to align the headers you have? This mainly includes, adding an @Date in the header, removing the change log in the header (this should be handled by git if anyone needs to see this) and where appropriate adding an @group tag (I have mainly followed the folders these are in for now)

Make sense, I'll update my classes now where appropriate

**Comment by KhinHou** [comment]
Ready to be reviewed @gavinhughpalmer

**Comment by gavinhughpalmer** [comment]
@KhinHou Thanks looks good! Merging in now

**Pull request merged**
